### ISSUE TITLE
Text doesn't seem to work

### ISSUE THREAD

**Issue by nasbah** [AlecAivazis/feynman-node#120]
Hello!

I like using this interface for Feynman diagrams but today I am not able to get "text" to work. Can you please help with this? 

Thanks!

Cheers,
     Alexandra

**Comment by AlecAivazis** [comment]
Yes, I'm aware. if you check this repo you will see the issue has been reported a lot. I know what the problem is but I can't seem to find a work around. Unforunately, i have a lot of projects on my plate and i dont really use this often enough to warrant the priority. sorry about that
